"""
Pydantic models for the Material Take-Off (MTO) data structure.

These are the single source of truth for the shape of data flowing through
the pipeline (Extractor -> Reader -> Verifier -> Normalizer) and out to the
frontend. Every stage of the pipeline validates against these models, so a
malformed LLM/OCR output fails loudly here rather than silently corrupting
the response.
"""
from __future__ import annotations

from typing import Literal, Optional
from pydantic import BaseModel, ConfigDict, Field

Category = Literal[
    "PIPE",
    "FITTING",
    "FLANGE",
    "VALVE",
    "GASKET",
    "BOLT",
    "SUPPORT",
    "INSTRUMENTATION",
]
Unit = Literal["M", "EA", "NO", "SET"]
VerificationStatus = Literal["match", "conflict", "unverified", "no_bom_available"]


SECTION_34_MTO_EXAMPLE = {
    "drawing_meta": {
        "drawing_no": "ISO-1501-01",
        "revision": "2",
        "line_number": '6"-P-1501-A1A-IH',
        "nps": '6"',
        "material_class": "A1A",
        "service": "Process",
    },
    "items": [
        {
            "item_no": 1,
            "category": "PIPE",
            "description": "Pipe, Seamless, BE, ASME B36.10",
            "size_nps": '6"',
            "schedule_rating": "SCH 40",
            "material_spec": "ASTM A106 Gr.B",
            "end_type": "BW",
            "quantity": 1,
            "unit": "M",
            "length_m": 12.45,
            "confidence": 0.92,
            "remarks": "",
        },
        {
            "item_no": 2,
            "category": "FITTING",
            "description": "Elbow 90 Deg LR, BW, ASME B16.9",
            "size_nps": '6"',
            "schedule_rating": "SCH 40",
            "material_spec": "ASTM A234 WPB",
            "end_type": "BW",
            "quantity": 4,
            "unit": "EA",
            "confidence": 0.88,
        },
    ],
    "summary": {
        "total_pipe_length_m": 12.45,
        "fittings": 4,
        "flanges": 2,
        "valves": 1,
        "gaskets": 2,
        "bolt_sets": 2,
        "field_welds": 1,
    },
}


class DrawingMeta(BaseModel):
    """Metadata read from the drawing's title block."""
    model_config = ConfigDict(json_schema_extra={"example": SECTION_34_MTO_EXAMPLE["drawing_meta"]})

    drawing_no: Optional[str] = None
    revision: Optional[str] = None
    line_number: Optional[str] = None
    nps: Optional[str] = None
    material_class: Optional[str] = None
    service: Optional[str] = None


class CoreMTOItem(BaseModel):
    """A single Section 3.4-style MTO row before pipeline enrichment."""
    model_config = ConfigDict(json_schema_extra={"example": SECTION_34_MTO_EXAMPLE["items"][0]})

    item_no: int
    category: Category
    description: str
    size_nps: Optional[str] = None
    schedule_rating: Optional[str] = None
    material_spec: Optional[str] = None
    end_type: Optional[str] = None
    quantity: float = Field(ge=0)
    unit: Unit
    length_m: Optional[float] = Field(default=None, ge=0)
    confidence: Optional[float] = Field(default=None, ge=0, le=1)
    remarks: Optional[str] = None


class MTOItem(CoreMTOItem):
    """A single MTO row enriched with review metadata generated by the pipeline."""
    source_page: Optional[int] = None

    # Fields added by our pipeline stages (not part of the raw LLM output):
    derived_from: Optional[str] = None
    verification_status: VerificationStatus = "unverified"


class MTOSummary(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                **SECTION_34_MTO_EXAMPLE["summary"],
                "supports": 0,
                "instrumentation_connections": 0,
            }
        }
    )

    total_pipe_length_m: float = 0
    fittings: int = 0
    flanges: int = 0
    valves: int = 0
    gaskets: int = 0
    bolt_sets: int = 0
    supports: int = 0
    instrumentation_connections: int = 0
    field_welds: int = 0


class CoreMTOResponse(BaseModel):
    """Core MTO payload aligned to the suggested Section 3.4 JSON shape."""
    model_config = ConfigDict(json_schema_extra={"example": SECTION_34_MTO_EXAMPLE})

    drawing_meta: DrawingMeta = Field(default_factory=DrawingMeta)
    items: list[CoreMTOItem] = Field(default_factory=list)
    summary: MTOSummary = Field(default_factory=MTOSummary)


class MTOResponse(CoreMTOResponse):
    """Top-level API response returned by POST /api/upload."""
    items: list[MTOItem] = Field(default_factory=list)
    needs_review: list[int] = Field(
        default_factory=list, description="item_no values flagged for manual review"
    )
    # Optional server-generated identifier for this result. Frontend should
    # use this `result_id` when requesting CSV/XLSX exports so the export
    # endpoints are deterministic and multi-user safe.
    result_id: Optional[str] = None
    mock: bool = Field(
        default=False, description="True if this response came from the mock pipeline (no API key configured)"
    )
    provider: str = Field(default="mock", description="'gemini' or 'mock'")
    mock_reason: Optional[str] = Field(
        default=None,
        description="Why the mock provider was used: missing_api_key, configured_mock_provider, gemini_error, or gemini_cooldown",
    )
    mock_details: Optional[str] = Field(
        default=None,
        description="Optional human-readable details about why the mock provider was used",
    )


JobStatus = Literal["pending", "processing", "complete", "failed"]


class JobInfo(BaseModel):
    job_id: str
    status: JobStatus
    detail: Optional[str] = None
    mto: Optional[MTOResponse] = None


class ErrorResponse(BaseModel):
    error: str
    detail: Optional[str] = None
